# Writes /boot/extlinux/extlinux.conf and the menu file U-Boot imports. Forked
# from generic-extlinux-compatible, whose addEntry() skips initrd-less systems.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.sheng.boot;

  installer = pkgs.writeShellApplication {
    name = "sheng-install-boot";
    runtimeInputs = with pkgs; [
      coreutils
      gnused
      gawk
    ];
    text = ''
      # usage: sheng-install-boot [-d <bootdir>] <toplevel>
      target=/boot
      while getopts "d:" o; do
        case "$o" in
          d) target="$OPTARG" ;;
          *) echo "usage: sheng-install-boot [-d bootdir] <toplevel>" >&2; exit 1 ;;
        esac
      done
      shift $((OPTIND - 1))
      default="$1"
      limit=${toString cfg.configurationLimit}

      mkdir -p "$target/nixos" "$target/extlinux"
      declare -A kept

      # Call as `copyIn x; y=$result`: a subshell would not propagate kept[].
      copyIn() {
        local src dst
        src=$(readlink -f "$1")
        dst="$target/nixos/$(echo "$src" | sed 's|^/nix/store/||; s|/|-|g')"
        if [ ! -e "$dst" ]; then
          cp -r "$src" "$dst.tmp.$$"
          mv "$dst.tmp.$$" "$dst"
        fi
        kept["$dst"]=1
        result=$(basename "$dst")
      }

      # $1 = system path, $2 = LABEL suffix, $3 = MENU LABEL text
      label() {
        local p k d params
        p=$(readlink -f "$1")
        [ -e "$p/kernel" ] || return 0
        copyIn "$p/kernel"; k=$result
        copyIn "$(readlink -m "$p/dtbs")"; d=$result
        params=$(cat "$p/kernel-params")

        printf '\nLABEL nixos-%s\n' "$2"
        printf '  MENU LABEL %s\n' "$3"
        printf '  LINUX ../nixos/%s\n' "$k"
        printf '  FDT ../nixos/%s/%s\n' "$d" '${cfg.dtbName}'
        printf '  APPEND init=%s/init %s\n' "$p" "$params"
      }

      specialisationsOf() {
        local d
        for d in "$1"/specialisation/*; do
          [ -d "$d" ] || continue
          basename "$d"
        done
      }

      # $1 = system path, $2 = tag ("default" or a generation number)
      entry() {
        local p desc specs s
        p=$(readlink -f "$1")
        [ -e "$p/kernel" ] || return 0
        if [ "$2" = default ]; then
          desc="NixOS - Default"
        else
          desc="NixOS - Generation $2 ($(cat "$p/nixos-version"))"
        fi

        label "$p" "$2" "$desc"

        # A specialisation toplevel is a complete system, so label() takes one
        # unchanged and copyIn dedupes the kernel it shares with its parent.
        mapfile -t specs < <(specialisationsOf "$p")
        for s in ''${specs[@]+"''${specs[@]}"}; do
          label "$p/specialisation/$s" "$2-$s" "$desc - $s"
        done
      }

      tmp="$target/extlinux/.extlinux.conf.$$"
      {
        echo "# Generated by sheng-install-boot. Edits are lost on nixos-rebuild."
        echo "DEFAULT nixos-default"
        # No top-level MENU: pxe_utils would prompt for a typed string.
        echo "PROMPT 0"
        echo "TIMEOUT 1"
        entry "$default" default
      } > "$tmp"

      menutmp="$target/.sheng-bootmenu.env.$$"
      : > "$menutmp"

      # cmd/bootmenu.c stops at the first gap, so keep the indices contiguous.
      n=0

      # $1 = title, $2 = the LABEL to boot, empty for the default entry.
      menuEntry() {
        local cmd
        if [ -n "$2" ]; then
          cmd="setenv pxe_label_override nixos-$2; run bootlinux"
        else
          cmd="setenv pxe_label_override; run bootlinux"
        fi
        # Title must not contain '=': bootmenu splits on the first one.
        printf 'bootmenu_%d=%s=%s\n' "$n" "$1" "$cmd" >> "$menutmp"
        n=$((n + 1))
      }

      gens=()
      for link in /nix/var/nix/profiles/system-*-link; do
        [ -e "$link" ] || continue
        g=''${link##*/system-}
        g=''${g%-link}
        case "$g" in
          *[!0-9]*) continue ;;
        esac
        gens+=("$g")
      done

      ordered=()
      if [ ''${#gens[@]} -gt 0 ]; then
        mapfile -t ordered < <(printf '%s\n' "''${gens[@]}" | sort -nr | head -n "$limit")
      fi

      defpath=$(readlink -f "$default")

      # Empty at image build time: no profile links exist yet.
      defgen=
      for g in ''${ordered[@]+"''${ordered[@]}"}; do
        if [ "$(readlink -f /nix/var/nix/profiles/system-"$g"-link)" = "$defpath" ]; then
          defgen=$g
          break
        fi
      done

      # Split so a specialisation's name can sit between head and tail.
      if [ -n "$defgen" ]; then
        defts=$(date '+%Y-%m-%d %H:%M' \
          -d "@$(stat -c %Y /nix/var/nix/profiles/system-"$defgen"-link)")
        defhead="NixOS generation $defgen"
        deftail=" ($defts) [current]"
      else
        defhead="NixOS - Default"
        deftail=" ($(cat "$defpath/nixos-version" 2>/dev/null || echo unknown))"
      fi

      menuEntry "$defhead$deftail" ""
      mapfile -t defspecs < <(specialisationsOf "$defpath")
      for s in ''${defspecs[@]+"''${defspecs[@]}"}; do
        menuEntry "$defhead $s$deftail" "default-$s"
      done

      for g in ''${ordered[@]+"''${ordered[@]}"}; do
        link=/nix/var/nix/profiles/system-$g-link
        entry "$link" "$g" >> "$tmp"
        [ "$g" = "$defgen" ] && continue
        # No -L: it would follow into the store, where mtime is the epoch.
        ts=$(date '+%Y-%m-%d %H:%M' -d "@$(stat -c %Y "$link")")
        menuEntry "NixOS generation $g ($ts)" "$g"
        mapfile -t specs < <(specialisationsOf "$(readlink -f "$link")")
        for s in ''${specs[@]+"''${specs[@]}"}; do
          menuEntry "NixOS generation $g $s ($ts)" "$g-$s"
        done
      done

      printf 'bootmenu_%d=Reboot to fastboot (bootloader)=run rebootfastboot\n' \
        "$n" >> "$menutmp"

      mv -f "$tmp" "$target/extlinux/extlinux.conf"
      mv -f "$menutmp" "$target/sheng-bootmenu.env"

      # Only inside $target/nixos: /boot/Image and the dtb are the rescue path.
      for fn in "$target"/nixos/*; do
        [ -e "$fn" ] || continue
        if [ "''${kept[$fn]:-}" != 1 ]; then
          chmod -R +w -- "$fn"
          rm -rf -- "$fn"
        fi
      done

      sync
    '';
  };
in
{
  options.sheng.boot = {
    configurationLimit = lib.mkOption {
      type = lib.types.int;
      default = 10;
      description = "How many generations U-Boot's menu offers. bootmenu.c caps it at 99.";
    };

    dtbName = lib.mkOption {
      type = lib.types.str;
      default = "qcom/sm8550-xiaomi-sheng.dtb";
      description = "Device tree within the generation's `dtbs` directory, written into each FDT line.";
    };

    installer = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      description = "The installer, exposed so the image builder can run it at build time.";
    };
  };

  config = {
    sheng.boot.installer = installer;

    system.build.installBootLoader = lib.getExe installer;
    system.boot.loader.id = "sheng-extlinux";

    # Cannot be used here -- see the header.
    boot.loader.generic-extlinux-compatible.enable = false;
    boot.loader.grub.enable = false;
  };
}
