# Writes /boot/extlinux/extlinux.conf and the menu file U-Boot imports.
#
# Forked from generic-extlinux-compatible, whose addEntry() returns early
# unless $path/initrd exists -- and nixpkgs only creates it when
# boot.initrd.enable is on, which is what makes root=PARTLABEL= work here.
# The stock installer therefore emits a header with no LABELs at all.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.sheng.boot;

  installer = pkgs.writeShellApplication {
    name = "sheng-install-boot";
    runtimeInputs = with pkgs; [
      coreutils
      gnused
      gawk
    ];
    text = ''
      # usage: sheng-install-boot [-d <bootdir>] <toplevel>
      #
      # -d lets the image builder populate ./files/boot with the same code
      # that runs at activation.
      target=/boot
      while getopts "d:" o; do
        case "$o" in
          d) target="$OPTARG" ;;
          *) echo "usage: sheng-install-boot [-d bootdir] <toplevel>" >&2; exit 1 ;;
        esac
      done
      shift $((OPTIND - 1))
      default="$1"
      limit=${toString cfg.configurationLimit}

      mkdir -p "$target/nixos" "$target/extlinux"
      declare -A kept

      # Call as `copyIn x; y=$result`, never `y=$(copyIn x)`: a subshell would
      # not propagate kept[], and the prune loop would delete what it copied.
      copyIn() {
        local src dst
        src=$(readlink -f "$1")
        dst="$target/nixos/$(echo "$src" | sed 's|^/nix/store/||; s|/|-|g')"
        if [ ! -e "$dst" ]; then
          cp -r "$src" "$dst.tmp.$$"
          mv "$dst.tmp.$$" "$dst"
        fi
        kept["$dst"]=1
        result=$(basename "$dst")
      }

      # $1 = system path, $2 = tag ("default" or a generation number)
      entry() {
        local p k d label params
        p=$(readlink -f "$1")
        [ -e "$p/kernel" ] || return 0
        copyIn "$p/kernel"; k=$result
        copyIn "$(readlink -m "$p/dtbs")"; d=$result
        label=$(cat "$p/nixos-version")
        params=$(cat "$p/kernel-params")

        printf '\nLABEL nixos-%s\n' "$2"
        if [ "$2" = default ]; then
          printf '  MENU LABEL NixOS - Default\n'
        else
          printf '  MENU LABEL NixOS - Generation %s (%s)\n' "$2" "$label"
        fi
        printf '  LINUX ../nixos/%s\n' "$k"
        printf '  FDT ../nixos/%s/%s\n' "$d" '${cfg.dtbName}'
        printf '  APPEND init=%s/init %s\n' "$p" "$params"
      }

      tmp="$target/extlinux/.extlinux.conf.$$"
      {
        echo "# Generated by sheng-install-boot. Edits are lost on nixos-rebuild."
        echo "DEFAULT nixos-default"
        # Do NOT add a top-level MENU: it makes pxe_utils prompt for a typed
        # string, and this board has three buttons.
        echo "PROMPT 0"
        echo "TIMEOUT 1"
        entry "$default" default
      } > "$tmp"

      menutmp="$target/.sheng-bootmenu.env.$$"
      : > "$menutmp"

      gens=()
      for link in /nix/var/nix/profiles/system-*-link; do
        [ -e "$link" ] || continue
        g=''${link##*/system-}
        g=''${g%-link}
        case "$g" in
          *[!0-9]*) continue ;;
        esac
        gens+=("$g")
      done

      ordered=()
      if [ ''${#gens[@]} -gt 0 ]; then
        mapfile -t ordered < <(printf '%s\n' "''${gens[@]}" | sort -nr | head -n "$limit")
      fi

      # cmd/bootmenu.c stops at the first gap, so keep the indices contiguous.

      defpath=$(readlink -f "$default")

      # Empty at image build time: no profile links exist yet.
      defgen=
      for g in ''${ordered[@]+"''${ordered[@]}"}; do
        if [ "$(readlink -f /nix/var/nix/profiles/system-"$g"-link)" = "$defpath" ]; then
          defgen=$g
          break
        fi
      done

      if [ -n "$defgen" ]; then
        defts=$(date '+%Y-%m-%d %H:%M' \
          -d "@$(stat -c %Y /nix/var/nix/profiles/system-"$defgen"-link)")
        deftitle="NixOS generation $defgen ($defts) [current]"
      else
        deflabel=$(cat "$defpath/nixos-version" 2>/dev/null || echo unknown)
        deftitle="NixOS - Default ($deflabel)"
      fi
      printf 'bootmenu_0=%s=setenv pxe_label_override; run bootlinux\n' \
        "$deftitle" >> "$menutmp"

      n=1
      for g in ''${ordered[@]+"''${ordered[@]}"}; do
        link=/nix/var/nix/profiles/system-$g-link
        entry "$link" "$g" >> "$tmp"
        [ "$g" = "$defgen" ] && continue
        # No -L: it would follow into the store, where mtime is the epoch.
        ts=$(date '+%Y-%m-%d %H:%M' -d "@$(stat -c %Y "$link")")
        # Title must not contain '=': bootmenu splits on the first one.
        printf 'bootmenu_%d=NixOS generation %s (%s)=setenv pxe_label_override nixos-%s; run bootlinux\n' \
          "$n" "$g" "$ts" "$g" >> "$menutmp"
        n=$((n + 1))
      done

      printf 'bootmenu_%d=Reboot to fastboot (bootloader)=run rebootfastboot\n' \
        "$n" >> "$menutmp"

      mv -f "$tmp" "$target/extlinux/extlinux.conf"
      mv -f "$menutmp" "$target/sheng-bootmenu.env"

      # Only inside $target/nixos: /boot/Image and the dtb live one level up
      # and are what sheng.env's rescue path boots.
      for fn in "$target"/nixos/*; do
        [ -e "$fn" ] || continue
        if [ "''${kept[$fn]:-}" != 1 ]; then
          chmod -R +w -- "$fn"
          rm -rf -- "$fn"
        fi
      done

      sync
    '';
  };
in
{
  options.sheng.boot = {
    configurationLimit = lib.mkOption {
      type = lib.types.int;
      default = 10;
      description = ''
        How many generations U-Boot's menu offers. Bounded by bootmenu.c's
        MAX_COUNT of 99, by space in /boot, and by legibility on a panel
        navigated with two volume buttons.
      '';
    };

    dtbName = lib.mkOption {
      type = lib.types.str;
      default = "qcom/sm8550-xiaomi-sheng.dtb";
      description = ''
        Path of the device tree within the generation's `dtbs` directory,
        written into each entry's FDT line.
      '';
    };

    installer = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      description = ''
        The installer, exposed so the image builder can run it at build time
        with the same code that runs at activation.
      '';
    };
  };

  config = {
    sheng.boot.installer = installer;

    system.build.installBootLoader = lib.getExe installer;
    system.boot.loader.id = "sheng-extlinux";

    # Cannot be used here -- see the header.
    boot.loader.generic-extlinux-compatible.enable = false;
    boot.loader.grub.enable = false;
  };
}
