# Writes /boot/extlinux/extlinux.conf and the menu file U-Boot imports.
#
# Forked from generic-extlinux-compatible, which cannot work here. Its
# addEntry() starts:
#
#     if ! test -e $path/kernel -a -e $path/initrd; then return; fi
#
# and nixpkgs only creates $toplevel/initrd when boot.initrd.enable is on.
# This board has it off -- that is what makes root=PARTLABEL= work without
# udev -- so the test fails for every generation and the stock installer
# emits a header with no LABELs, plus an INITRD line pointing at nothing.
#
# Three deltas from upstream:
#
#   1. No initrd, required or emitted.
#   2. PROMPT 0 and no top-level MENU. A top-level MENU sets cfg->prompt
#      in pxe_utils, which routes to cli_readline_into_buffer("Enter
#      choice: ") and matches a typed string. This board has three
#      buttons. U-Boot's own bootmenu does the selecting, via
#      pxe_label_override. MENU LABEL inside a LABEL is fine.
#   3. Also writes /boot/sheng-bootmenu.env, the bootmenu_<n> lines
#      sheng.env imports. U-Boot cannot enumerate generations itself:
#      hush has no directory listing and no command substitution.
#
# FDT is explicit, never FDTDIR. FDTDIR needs $fdtfile, which sheng.env
# does not define, and would leave U-Boot guessing by compatible string
# instead of using the overlaid DTB.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.sheng.boot;

  installer = pkgs.writeShellApplication {
    name = "sheng-install-boot";
    runtimeInputs = with pkgs; [
      coreutils
      gnused
      gawk
    ];
    text = ''
      # usage: sheng-install-boot [-d <bootdir>] <toplevel>
      #
      # -d exists so the image builder can populate ./files/boot at build
      # time with exactly the same code that runs at activation time.
      target=/boot
      while getopts "d:" o; do
        case "$o" in
          d) target="$OPTARG" ;;
          *) echo "usage: sheng-install-boot [-d bootdir] <toplevel>" >&2; exit 1 ;;
        esac
      done
      shift $((OPTIND - 1))
      default="$1"
      limit=${toString cfg.configurationLimit}

      mkdir -p "$target/nixos" "$target/extlinux"
      declare -A kept

      # Copies a store path under $target/nixos, flattened, and reports
      # the name in $result. Idempotent.
      #
      # Call as `copyIn x; y=$result`, never `y=$(copyIn x)`. Command
      # substitution is a subshell, so kept[] would not reach the parent
      # and the prune loop below would delete everything just copied.
      copyIn() {
        local src dst
        src=$(readlink -f "$1")
        dst="$target/nixos/$(echo "$src" | sed 's|^/nix/store/||; s|/|-|g')"
        if [ ! -e "$dst" ]; then
          cp -r "$src" "$dst.tmp.$$"
          mv "$dst.tmp.$$" "$dst"
        fi
        kept["$dst"]=1
        result=$(basename "$dst")
      }

      # $1 = system path, $2 = tag ("default" or a generation number)
      entry() {
        local p k d label params
        p=$(readlink -f "$1")
        # No initrd test -- see the header. Only the kernel is required.
        [ -e "$p/kernel" ] || return 0
        # Not $(copyIn ...) -- see the comment on copyIn.
        copyIn "$p/kernel"; k=$result
        copyIn "$(readlink -m "$p/dtbs")"; d=$result
        label=$(cat "$p/nixos-version")
        params=$(cat "$p/kernel-params")

        printf '\nLABEL nixos-%s\n' "$2"
        if [ "$2" = default ]; then
          printf '  MENU LABEL NixOS - Default\n'
        else
          printf '  MENU LABEL NixOS - Generation %s (%s)\n' "$2" "$label"
        fi
        printf '  LINUX ../nixos/%s\n' "$k"
        printf '  FDT ../nixos/%s/%s\n' "$d" '${cfg.dtbName}'
        printf '  APPEND init=%s/init %s\n' "$p" "$params"
      }

      tmp="$target/extlinux/.extlinux.conf.$$"
      {
        echo "# Generated by sheng-install-boot. Edits are lost on nixos-rebuild."
        echo "DEFAULT nixos-default"
        # See header delta 2. Do NOT add a top-level MENU line.
        echo "PROMPT 0"
        echo "TIMEOUT 1"
        entry "$default" default
      } > "$tmp"

      menutmp="$target/.sheng-bootmenu.env.$$"
      : > "$menutmp"

      # Collected with a glob rather than `ls`: no parsing of ls output,
      # and a glob that matches nothing simply skips the loop body.
      gens=()
      for link in /nix/var/nix/profiles/system-*-link; do
        [ -e "$link" ] || continue
        g=''${link##*/system-}
        g=''${g%-link}
        # Skip anything that is not purely a generation number.
        case "$g" in
          *[!0-9]*) continue ;;
        esac
        gens+=("$g")
      done

      ordered=()
      if [ ''${#gens[@]} -gt 0 ]; then
        mapfile -t ordered < <(printf '%s\n' "''${gens[@]}" | sort -nr | head -n "$limit")
      fi

      # This file defines the whole menu, index 0 included, so entries are
      # named after the generation that will boot. sheng.env's static
      # bootmenu_0/bootmenu_1 are only the fallback: `env import`
      # overwrites exactly what this file defines, so they survive if it
      # never loads.
      #
      # cmd/bootmenu.c stops at the first gap; keep indices contiguous.

      defpath=$(readlink -f "$default")

      # Empty at image build time: no profile links exist yet, so the
      # image ships one entry for the system baked into it.
      defgen=
      for g in ''${ordered[@]+"''${ordered[@]}"}; do
        if [ "$(readlink -f /nix/var/nix/profiles/system-"$g"-link)" = "$defpath" ]; then
          defgen=$g
          break
        fi
      done

      # No pxe_label_override, so extlinux.conf's DEFAULT decides. Going
      # through DEFAULT keeps entry 0 working even if a label is absent.
      if [ -n "$defgen" ]; then
        # Same timestamp source as the entries below, so all rows read
        # alike rather than this one showing a version string.
        defts=$(date '+%Y-%m-%d %H:%M' \
          -d "@$(stat -c %Y /nix/var/nix/profiles/system-"$defgen"-link)")
        deftitle="NixOS generation $defgen ($defts) [current]"
      else
        # Image build time: no profile links exist yet, so there is no
        # generation number or creation time to show. The version label
        # is the only meaningful thing available.
        deflabel=$(cat "$defpath/nixos-version" 2>/dev/null || echo unknown)
        deftitle="NixOS - Default ($deflabel)"
      fi
      printf 'bootmenu_0=%s=setenv pxe_label_override; run bootlinux\n' \
        "$deftitle" >> "$menutmp"

      n=1
      for g in ''${ordered[@]+"''${ordered[@]}"}; do
        link=/nix/var/nix/profiles/system-$g-link
        entry "$link" "$g" >> "$tmp"
        # Already offered as entry 0; listing it twice is just noise.
        [ "$g" = "$defgen" ] && continue
        # No -L: it would follow into the store, where mtime is the
        # epoch. The link's own mtime is when the generation was made.
        ts=$(date '+%Y-%m-%d %H:%M' -d "@$(stat -c %Y "$link")")
        # Title must not contain '=': bootmenu splits on the first one.
        printf 'bootmenu_%d=NixOS generation %s (%s)=setenv pxe_label_override nixos-%s; run bootlinux\n' \
          "$n" "$g" "$ts" "$g" >> "$menutmp"
        n=$((n + 1))
      done

      # Fastboot last. rebootfastboot itself is defined in sheng.env.
      printf 'bootmenu_%d=Reboot to fastboot (bootloader)=run rebootfastboot\n' \
        "$n" >> "$menutmp"

      mv -f "$tmp" "$target/extlinux/extlinux.conf"
      mv -f "$menutmp" "$target/sheng-bootmenu.env"

      # Prune only inside $target/nixos. /boot/Image and the dtb live one
      # level up and are what sheng.env's rescue path boots.
      for fn in "$target"/nixos/*; do
        [ -e "$fn" ] || continue
        if [ "''${kept[$fn]:-}" != 1 ]; then
          chmod -R +w -- "$fn"
          rm -rf -- "$fn"
        fi
      done

      sync
    '';
  };
in
{
  options.sheng.boot = {
    configurationLimit = lib.mkOption {
      type = lib.types.int;
      default = 10;
      description = ''
        How many generations U-Boot's menu offers.

        Bounded by three things in increasing tightness: cmd/bootmenu.c's
        MAX_COUNT of 99; space in /boot (~40 MiB of kernel per
        generation, on the root filesystem); and legibility on a panel
        navigated with two volume buttons.
      '';
    };

    dtbName = lib.mkOption {
      type = lib.types.str;
      default = "qcom/sm8550-xiaomi-sheng.dtb";
      description = ''
        Path of the device tree within the generation's `dtbs` directory,
        written into each entry's FDT line.
      '';
    };

    installer = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      description = ''
        The installer itself, exposed so ../rootfs/builder.nix can run it
        at image-build time against `./files/boot` with the same code
        that runs at activation.
      '';
    };
  };

  config = {
    sheng.boot.installer = installer;

    system.build.installBootLoader = lib.getExe installer;
    system.boot.loader.id = "sheng-extlinux";

    # Cannot be used here -- see the header.
    boot.loader.generic-extlinux-compatible.enable = false;
    boot.loader.grub.enable = false;
  };
}
